# Generated by Django 3.0.3 on 2020-03-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_workers_done_report', 'Просмотр отчета по прошедшим'),)},
        ),
    ]
