# Generated by Django 3.0.3 on 2020-07-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_directiondocxtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_workers_done_report', 'Просмотр отчета по прошедшим'), ('view_money', 'Просмотр денежной информации'), ('view_direction', 'Просмотр направлений на осмотр'), ('add_direction', 'Создание направлений на осмотр'), ('change_direction', 'Редактирование направлений на осмотр'), ('delete_direction', 'Удаление направлений на осмотр'))},
        ),
    ]
