# Generated by Django 3.0.3 on 2020-03-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200313_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='valuable_service_ids',
        ),
    ]
