# Generated by Django 3.0.7 on 2021-01-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200710_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
    ]
