# Generated by Django 3.0.7 on 2021-01-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvailableDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type_id', models.IntegerField(verbose_name='ID вида документа в МИС')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступный вид документа для пользователя',
                'verbose_name_plural': 'Доступные виды документов для пользователей',
                'unique_together': {('user', 'document_type_id')},
            },
        ),
    ]
