# Generated by Django 3.0.7 on 2021-03-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_useravailabledocumenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='birth',
            field=models.DateField(null=True, verbose_name='Дата рождение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(default='', max_length=7, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='worker',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='useravailabledocumenttype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_document_type_ids', to='core.User', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='WorkerOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_id', models.IntegerField(verbose_name='МИС id')),
                ('org_id', models.IntegerField(verbose_name='Организация id')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('shop', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник_Организация',
            },
        ),
    ]
