# Generated by Django 3.0.7 on 2021-03-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210329_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['last_name', 'first_name', 'middle_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='workerorganization',
            options={'verbose_name': 'Сотрудник_Организация', 'verbose_name_plural': 'Сотрудник_Организация'},
        ),
        migrations.AddField(
            model_name='workerorganization',
            name='end_work_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата уволения'),
        ),
        migrations.AddField(
            model_name='workerorganization',
            name='start_work_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth',
            field=models.DateField(verbose_name='Дата рождение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='workerorganization',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_org', to='core.Worker', verbose_name='Сотрудник'),
        ),
    ]
