# Generated by Django 3.0.7 on 2021-05-06 15:12

from django.db import migrations, models
import django.db.models.deletion


def exists_user_password_change_required_false(apps, schema_editor):
    """ Для существующих пользователей оставим необязательность смены пароля """
    User = apps.get_model('core', 'User')
    User.objects.all().update(need_change_password=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210331_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='need_change_password',
            field=models.BooleanField(default=True, verbose_name='Временный пароль'),
        ),
        migrations.AlterField(
            model_name='workerorganization',
            name='shop',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='workerorganization',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_orgs', to='core.Worker', verbose_name='Сотрудник'),
        ),
        migrations.RunPython(exists_user_password_change_required_false, reverse_code=migrations.RunPython.noop)
    ]
