# Generated by Django 3.0.7 on 2021-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210506_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='need_change_password',
            field=models.BooleanField(default=True, verbose_name='Нужно сменить пароль'),
        ),
        migrations.AlterField(
            model_name='workerorganization',
            name='post',
            field=models.CharField(max_length=512, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='workerorganization',
            name='shop',
            field=models.CharField(blank=True, max_length=512, verbose_name='Подразделение'),
        ),
    ]
