# Generated by Django 3.0.7 on 2021-05-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
