# Generated by Django 3.2.5 on 2021-12-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210813_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['last_name', 'first_name', 'middle_name'], 'permissions': (('view_workers_document', 'Просмотр документов сотрудника'),), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='workerorganization',
            options={'verbose_name': 'Сотрудник организации', 'verbose_name_plural': 'Сотрудники организации'},
        ),
    ]
