# Generated by Django 3.2.5 on 2021-12-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211206_1806'),
        ('core', '0011_auto_20211208_0055'),
    ]

    operations = [
    ]
