# Generated by Django 3.2.5 on 2021-12-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_0011_auto_20211206_1806_0011_auto_20211208_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_policy', models.CharField(blank=True, max_length=255, verbose_name='Cтраховой полис')),
                ('org_id', models.IntegerField(blank=True, null=True, verbose_name='Организация id')),
                ('post', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('shop', models.CharField(blank=True, max_length=255, verbose_name='Подразделение')),
                ('exam_type', models.CharField(choices=[('Предварительный', 'Предварительный'), ('Периодический', 'Периодический'), ('Внеочередной', 'Внеочередной')], max_length=255, verbose_name='Вид осмотра')),
                ('pay_method', models.CharField(max_length=255, verbose_name='Cпособ оплаты')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_directions', to='core.worker', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='DirectionLawItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_item_mis_id', models.CharField(max_length=255, verbose_name='Пункты приказа')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.direction', verbose_name='Направление')),
            ],
        ),
    ]
