# Generated by Django 3.2.5 on 2021-12-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_direction_directionlawitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направление'},
        ),
        migrations.AlterModelOptions(
            name='directionlawitem',
            options={'verbose_name': 'Пункты приказа', 'verbose_name_plural': 'Пункты приказа'},
        ),
        migrations.AddField(
            model_name='direction',
            name='mis_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='МИС id'),
        ),
    ]
