STATUS_PENDING = 'Ожидает выполнения'
STATUS_IN_PROCESS = 'В процессе выполнения'
STATUS_COMPLETE = 'Завершено'
STATUS_FAIL = 'Не удалось выполнить'
STATUS_CANCEL = 'Отменено'

STATUS_CHOICES = (
    (STATUS_PENDING, STATUS_PENDING),
    (STATUS_IN_PROCESS, STATUS_IN_PROCESS),
    (STATUS_COMPLETE, STATUS_COMPLETE),
    (STATUS_FAIL, STATUS_FAIL),
    (STATUS_CANCEL, STATUS_CANCEL),
)
