# Generated by Django 2.1.5 on 2019-02-16 08:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, создавший задачу', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('func_path', models.CharField(max_length=255, verbose_name='Функция для вызова')),
                ('params', models.FileField(blank=True, help_text='Параметры, сериализованные в формате pickle', null=True, upload_to='', verbose_name='Параметры')),
                ('status', models.CharField(choices=[('Ожидает выполнения', 'Ожидает выполнения'), ('В процессе выполнения', 'В процессе выполнения'), ('Завершено', 'Завершено'), ('Не удалось выполнить', 'Не удалось выполнить'), ('Отменено', 'Отменено')], db_index=True, default='Ожидает выполнения', max_length=255, verbose_name='Статус выполнения задачи')),
                ('percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент выполнения')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('start_dt', models.DateTimeField(blank=True, null=True, verbose_name='Время начала выполнения задачи')),
                ('finish_dt', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания выполнения задачи')),
                ('result_attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Фоновая задача',
                'verbose_name_plural': 'Фоновые задачи',
                'ordering': ('-created_dt',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='background_tasks.Task')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('Ожидает выполнения', 'Ожидает выполнения'), ('В процессе выполнения', 'В процессе выполнения'), ('Завершено', 'Завершено'), ('Не удалось выполнить', 'Не удалось выполнить'), ('Отменено', 'Отменено')], db_index=True, default='В процессе выполнения', max_length=255, verbose_name='Статус выполнения задачи')),
                ('dc', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Запись журнала выполнения задачи',
                'verbose_name_plural': 'Журнал выполнения задачи',
                'ordering': ('-dc',),
            },
        ),
    ]
