name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run --source='core' --omit='*migrations*,*tests*' manage.py test -v 2 core && coverage report
#    - name: Deploy Stage
#      run: |
#          ansible-playbook -i ansible/inventory -u root -v ansible/install.yml -e "web_server_name=med-org-portal service_port=8030 dockerhub_login=${{ secrets.dockerhub_login }} dockerhub_password=${{ secrets.dockerhub_password }} dockerhub_email=${{ secrets.dockerhub_email }} MIS_URL=${{ secrets.mis_url }} MIS_TOKEN=${{ secrets.mis_token }} SECRET_KEY=${{ secrets.SECRET_KEY }} DEBUG=${{ secrets.DEBUG }}"