#name: Django CI
#on:
#  push:
#    branches: [ master ]
##  pull_request:
##    branches: [ master ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build Docker Image
#      run: |
#        docker build . --file Dockerfile --pull -t ${{ secrets.DOCKER_REGISTRY }}
#        docker push ${{ secrets.DOCKER_REGISTRY }}
#
#  test:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#    - name: Run Tests
#      run: |
#        docker pull ${{ secrets.DOCKER_REGISTRY }}
#        docker run --rm ${{ secrets.DOCKER_REGISTRY }} bash -c "coverage run --source='core' --omit='*migrations*,*tests*' manage.py test -v 2 core && coverage report"
