name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --pull -t ${{ secrets.DOCKER_REGISTRY }}
        docker push ${{ secrets.DOCKER_REGISTRY }}
    - name: Run Tests
      run: |
        docker pull ${{ secrets.DOCKER_REGISTRY }}
        docker run --rm ${{ secrets.DOCKER_REGISTRY }} bash -c "coverage run --source='core' --omit='*migrations*,*tests*' manage.py test -v 2 core && coverage report"

#    - uses: webfactory/ssh-agent@v0.2.0
#      with:
#        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#    - name: Deploy Stage
#      run: |
#          ansible-playbook -i ansible/inventory -u root -v ansible/install.yml -e "web_server_name=med-org-portal service_port=8030 dockerhub_login=${{ secrets.dockerhub_login }} dockerhub_password=${{ secrets.dockerhub_password }} dockerhub_email=${{ secrets.dockerhub_email }} MIS_URL=${{ secrets.mis_url }} MIS_TOKEN=${{ secrets.mis_token }} SECRET_KEY=${{ secrets.SECRET_KEY }} DEBUG=${{ secrets.DEBUG }}"
